<?xml version="1.0" encoding="utf-8"?><Database Name="StateInfo" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\StateInfo.mdf;Integrated Security=True" SettingsObjectName="andrew_foster_cpt_206_lab_2.Properties.Settings" SettingsPropertyName="StateInfoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="state" Member="state1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="flag" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="flower" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="bird" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="colors" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="population" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="first_city" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="second_city" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="third_city" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="capitol" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="income" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="it_jobs" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>